version: "3.8"

services:
  mongodb-interview:
    image: mongo:latest
    container_name: mongodb-interview
    ports:
      - "27020:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_interview_data:/data/db

volumes:
  mongo_interview_data:
